### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by martcpp**
corrected how to run pnpm so those who don have the package install in their system can install and get started

### CODE REVIEW

**Comment by martcpp** [comment]
@zerolee1231 @geekan review

**Comment by zerolee1231** [comment]
@martcpp  Node.js v18 and above now come with CorePack built-in. I highly recommend using CorePack to manage package management tools. It's similar to using NVM to manage Node.js instead of directly installing a specific Node.js version.

**Comment by martcpp** [comment]
Not everyone what to us node 18 so why Force them to use core pack make projects flexible for all

**Comment by zerolee1231** [comment]
> Not everyone what to us node 18 so why Force them to use core pack make projects flexible for all

vitepress require nodejs v18+.  and maybe link https://pnpm.io/installation here  is better way

**Pull request closed without merging**
